# Generated by Django 6.1.1 on 2026-09-29 03:29

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference", "0002_seed_reference_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NGOProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                ("registration_number", models.CharField(max_length=64)),
                ("registering_authority", models.CharField(max_length=200)),
                (
                    "timezone",
                    models.CharField(
                        max_length=64,
                        validators=[core.validators.validate_iana_timezone],
                    ),
                ),
                (
                    "official_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a phone number in international format, e.g. +923001234567.",
                                regex="^\\+[1-9]\\d{6,14}$",
                            )
                        ],
                    ),
                ),
                ("official_email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.country",
                    ),
                ),
                (
                    "registration_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ngo_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NGO profile",
            },
        ),
        migrations.CreateModel(
            name="NGOServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.country",
                    ),
                ),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="ngo.ngoprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ngoprofile",
            constraint=models.UniqueConstraint(
                fields=("registration_country", "registration_number"),
                name="ngo_unique_registration_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="ngoservicearea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("city__isnull", True)),
                fields=("ngo", "country"),
                name="ngo_service_area_unique_nationwide",
            ),
        ),
        migrations.AddConstraint(
            model_name="ngoservicearea",
            constraint=models.UniqueConstraint(
                condition=models.Q(("city__isnull", False)),
                fields=("ngo", "country", "city"),
                name="ngo_service_area_unique_city",
            ),
        ),
    ]
