# Generated by Django 6.1.1 on 2026-09-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="adult_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
