# Generated by Django 6.1.1 on 2026-10-06 03:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("psychologists", "0002_psychologistprofile_is_accepting_patients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("ended", "Ended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("outside_specializations", "Outside my specializations"),
                            (
                                "language_or_timezone_mismatch",
                                "Language or time-zone mismatch",
                            ),
                            ("case_type_not_taken", "Not taking this type of case"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient", "Patient"),
                            ("psychologist", "Psychologist"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("treatment_completed", "Treatment completed"),
                            ("referred_elsewhere", "Referred to another professional"),
                            ("other", "Other"),
                            ("patient_ended", "Ended by the patient"),
                            ("account_unavailable", "Account unavailable"),
                            ("subscription_lapsed", "Subscription lapsed"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_relationships",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="care_relationships",
                        to="psychologists.psychologistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["psychologist", "status"],
                        name="relationships_psych_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "accepted"])),
                        fields=("patient",),
                        name="relationships_one_open_per_patient",
                    )
                ],
            },
        ),
    ]
