# Generated by Django 6.1.1 on 2026-09-28 18:46

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference", "0002_seed_reference_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychologistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=64)),
                ("license_issuing_authority", models.CharField(max_length=200)),
                ("qualifications", models.TextField(max_length=1000)),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(70)]
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        max_length=64,
                        validators=[core.validators.validate_iana_timezone],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.country",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(related_name="+", to="reference.language"),
                ),
                (
                    "license_issuing_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference.country",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        related_name="+", to="reference.specialization"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychologist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("license_issuing_country", "license_number"),
                        name="psychologists_unique_license_per_country",
                    )
                ],
            },
        ),
    ]
