# Generated by Django 6.1.1 on 2026-10-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("psychologists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologistprofile",
            name="is_accepting_patients",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="not_accepting_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fully_booked", "Fully booked"),
                    ("away", "Away / on leave"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
